import Head from "next/head";
import Navbar from "~/components/Navbar";
import { Spotlight } from "~/components/ui/Spotlight";

function SpotlightName() {
  return (
    <div className="bg-grid-white/[0.02] relative flex h-[40rem] w-full overflow-hidden rounded-md antialiased md:items-center md:justify-center">
      <Spotlight
        className="-top-40 left-0 md:-top-20 md:left-60"
        fill="white"
      />
      <div className="relative z-10 mx-auto  w-full max-w-7xl p-4  pt-20 hover:cursor-pointer md:pt-0">
        <h1 className="bg-opacity-50 bg-gradient-to-b from-neutral-50 to-neutral-400 bg-clip-text text-center text-4xl font-bold text-transparent md:text-7xl">
          <span className="transition-all hover:border-b-2">Code Crafters</span>
        </h1>
        <p className="mx-auto mt-4 max-w-lg text-center text-base font-normal text-neutral-300">
          Inspiring Minds, One Post at a Time
        </p>
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Visualizing purposes */}
        <section className="bg-green-500">
          <Navbar />
        </section>
        <section className="bg-red-500">
          <SpotlightName />
        </section>
      </main>
    </>
  );
}
